### ISSUE TITLE
Issue with Patching

### ISSUE THREAD

**Issue by Apolishspy** [googleben/EmeraldPartyRandomizer#3]
When i patch the emerald #1986 file with this patch it says it cannot because i am on read only however i don't know how to fix that.

**Comment by googleben** [comment]
Ensure that your Emerald ROM is in a location you have permissions to modify, such as your documents folder on Windows, or your desktop on Mac OS. For more help, see [Google](https://www.google.com/search?q=file+is+read+only).

**Comment by Apolishspy** [comment]
Hey man thanks I found that issue and fixed it myself got it working but
thanks for the input.
