### ISSUE TITLE
Rom #1986 Is not Randomizing

### ISSUE THREAD

**Issue by XiledPhoenix** [googleben/EmeraldPartyRandomizer#4]
I downloaded the rom and the randomizer, but when I load the game it doesnt randomize my party. I tried patching the rom but it wont do anything. It says that it can not find the patch file. Please help. I really want to use this mod. It looks like so much fun.

**Comment by googleben** [comment]
Ensure that you follow the instructions to download the patch file and patch using FLIPS.
